# betty
# Autogenerated from man page /usr/local/man/man1/betty.1
complete -c betty -l ------------------------------------------ --description 'if			Yes			if (condition) else if		Yes			else if (condition) switch		Yes			sw…'
complete -c betty -l 'i;' --description 'And no space around the .  and -> structure member operators.'

