# betty-doc
# Autogenerated from man page /usr/local/man/man1/betty-doc.1
complete -c betty-doc -o docbook --description '.'
complete -c betty-doc -o html --description '.'
complete -c betty-doc -o html5 --description '.'
complete -c betty-doc -o list --description '.'
complete -c betty-doc -o man --description '.'
complete -c betty-doc -o rst --description '.'
complete -c betty-doc -o text --description '.'
complete -c betty-doc -o function --description 'Only output documentation for the given function(s) or DOC: section title(s).'
complete -c betty-doc -o nofunction --description 'Do NOT output documentation for the given function(s).'
complete -c betty-doc -o no-doc-sections --description 'Do not output DOC: sections.  Other parameters:.'
complete -c betty-doc -s v --description '.'
complete -c betty-doc -s h --description '.'

